### PR TITLE
fix: make uploads resumable

### PR DESCRIPTION
**Pull request by digitalsadhu**
Haven't managed to get my local copy setup for testing yet (need gcloud credentials etc) but after some digging, this seemed like it might solve upload issues. Could well be off base here. Thoughts?

ref:
* https://cloud.google.com/storage/docs/uploads-downloads
* https://cloud.google.com/storage/docs/performing-resumable-uploads

### CODE REVIEW

**Review by leftieFriele — APPROVED** [review]
Makes sense to me to have it be a resumable upload, I think it's even the default so you could consider removing the attribute all together.

**Comment by wkillerud** [comment]
Looking at https://googleapis.dev/nodejs/storage/latest/File.html#createResumableUpload

> If you are just looking to perform a resumable upload without worrying about any of the details, see [File#createWriteStream](https://googleapis.dev/nodejs/storage/latest/File.html#createWriteStream). Resumable uploads are performed by default.

So I don't think we need the added call to `createResumableUpload` unless we want to save the URI and do some micromanagement ourselves.

**Comment by wkillerud** [comment]
On the failing test:

> timeout: Set the HTTP request timeout in milliseconds. This option is not available for resumable uploads. Default: 60000

I'm looking into why we set resumable to false to begin with.

**Comment by wkillerud** [comment]
`resumable: false` was in [the initial commit](https://github.com/eik-lib/sink-gcs/commit/353fe212f9642813efe1c622629063159f80f712#diff-7934bf411fea192ad8cd69e0a12911648a2842cb0f2409a8fb67b41b7069d757). The timeout option from https://github.com/eik-lib/sink-gcs/pull/38

**Comment by wkillerud** [comment]
I'm trying to understand the existing behavior and what this change would accomplish. From what I can tell there are two points where an upload can fail:

1. Source machine (CI or developer's machine) to Eik
2. Eik to GCloud

To the source machine this all seems like one request (the response is not sent untill the GCloud upload is complete).

[The multipart-parser in core](https://github.com/eik-lib/core/blob/92098d234a7b2c4353d015344a532c114feb61a1/lib/multipart/parser.js#L181) is what writes the actual package files to the sink. That parser is called by [the PUT handler for packages](https://github.com/eik-lib/core/blob/92098d234a7b2c4353d015344a532c114feb61a1/lib/handlers/pkg.put.js#L70).

The change in this PR would make Eik to GCloud resumable (in theory), but what does that accomplish? How will that upload be resumed? Do we return the resumable URL to the source machine? Add retry-logic to the `write` method?

```js
// from https://googleapis.dev/nodejs/storage/latest/File.html#createWriteStream-examples
//-
// <h4>Continuing a Resumable Upload</h4>
//
// One can capture a `uri` from a resumable upload to reuse later.
// Additionally, for validation, one can also capture and pass `crc32c`.
//-
let uri: string | undefined = undefined;
let resumeCRC32C: string | undefined = undefined;

fs.createWriteStream()
  .on('uri', link => {uri = link})
  .on('crc32', crc32c => {resumeCRC32C = crc32c});

// later...
fs.createWriteStream({uri, resumeCRC32C});
```

**Comment by wkillerud** [comment]
I think a short-term workaround is perhaps to increase the [timeout to its default `60000`](https://googleapis.dev/nodejs/storage/latest/global.html#CreateWriteStreamOptions) rather than [halving it to `30000`](https://github.com/eik-lib/sink-gcs/blob/cf7393f78cb2f275270a855c4949094ca119f3b3/lib/main.js#L19).

**Comment by wkillerud** [comment]
From @trygve-lie: `resumable: false` was turned on because we typically upload small files, and [the docs recommend it](https://googleapis.dev/nodejs/storage/latest/File.html#createWriteStream) in that case.

> When uploading files less than 10MB, it is recommended that the resumable feature is disabled.

**Comment by wkillerud** [comment]
Summarising some findings that were made in our Slack

> We are also a bit in the blind here; we seems to be missing logs if extracting the file errors: https://github.com/eik-lib/core/blob/master/lib/multipart/parser.js#L134-L150 We should a bit of error logging here. 
>
> When the tar file is extracted on the server, each file inside the tar file if written to GCS: https://github.com/eik-lib/core/blob/master/lib/multipart/parser.js#L129
> 300 files in a tar file will open 300 write streams to GCS. It might be that we should apply a proper queue to control and batch these write streams instead of firing off 300 at once. https://github.com/eik-lib/core/blob/master/lib/multipart/parser.js#L129

I made a couple of issues in eik-lib/core:

- https://github.com/eik-lib/core/issues/418
- https://github.com/eik-lib/core/issues/419

**Comment by digitalsadhu** [comment]
Nice sleuthing!

**Pull request merged**
